const EVENTO_LOGIN = "LOGIN_GENERAL";
const EVENTO_LOGIN_ADMIN = "LOGIN_ADMIN";
const ID_CARGO_COLEGIATURA = 1;
const ID_TIPO_USUARIO_MAESTRA = 1;

const CONSTANTES = {
    EVENTO_LOGIN: EVENTO_LOGIN,
    EVENTO_LOGIN_ADMIN: EVENTO_LOGIN_ADMIN,
    ID_CARGO_COLEGIATURA: ID_CARGO_COLEGIATURA,
    ID_CARGO_INCRIPCION: 2,
    ID_TIPO_USUARIO_MAESTRA: ID_TIPO_USUARIO_MAESTRA,
    ID_ROL_VER_DASHBOARD: 9,
    ID_ROL_GERENTE: 1,
    ID_ROL_ADMINISTRADOR: 8
};

export default CONSTANTES;